### ISSUE TITLE
Enabling one_packet : true

### ISSUE THREAD

**Issue by DefenceLogic** [google/seesaw#102]
Hi ,

I am trying to enable the one_packet : true configuration in my vserver_entry as per #99 

I have the following snippet.

```
vserver_entry: 
    protocol: UDP
    port: 12210
    scheduler: RR
    one_packet: true
    mode: NAT
    healthcheck: <
      type: TCP
      port: 32999
      tls_verify: false
      interval: 10
      timeout: 5
      retries: 3
    >
```

When I try to start seesaw, I get the following error message:
`
Failed to load cluster config from disk: line 54: unknown field name "vserver" in config.Vserver
`

If I remove the one_packet : true directive Seesaw starts properly. 

Did I place the one_packet:true directive in the wrong place?

Cheers

Cyberkryption
